version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rcs
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  # app:
  #   build: .
  #   restart: always
  #   environment:
  #     NODE_ENV: production
  #     DATABASE_URL: postgres://postgres:password@db:5432/rcs
  #   volumes:
  #     - .:/app
  #   ports:
  #     - '8080:8080'
  #   depends_on:
  #     - db
volumes:
  db-data:
